[package]
name = "spongebob"
version = "0.1.1"
authors = ["Dave Lucia <davelucianyc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
cli-clipboard = "0.2.0"
clap = "3.0.0-beta.2"
