name: spongebob # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: SPongEbOB IS BuiLT WiTH lOve foR aLl YOuR SarCAsTIc NEEds # 79 char long summary
description: |
  Spongebob is a command-line tool for making your text sound sarcastic.
  Teh intertubez require this from time to time.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  spongebob:
    source: .
    # See 'snapcraft plugins'
    plugin: rust
    stage-packages:
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
apps:
  spongebob:
    command: bin/spongebob
    plugs:
      - wayland
      - x11
